[2023-12-03T19:16:27.710+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_scrapper.create_table manual__2023-12-03T19:16:25.432817+00:00 [queued]>
[2023-12-03T19:16:27.724+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_scrapper.create_table manual__2023-12-03T19:16:25.432817+00:00 [queued]>
[2023-12-03T19:16:27.725+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-03T19:16:27.742+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): create_table> on 2023-12-03 19:16:25.432817+00:00
[2023-12-03T19:16:27.748+0000] {standard_task_runner.py:57} INFO - Started process 359 to run task
[2023-12-03T19:16:27.752+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'weather_scrapper', 'create_table', 'manual__2023-12-03T19:16:25.432817+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/weather_scrapper.py', '--cfg-path', '/tmp/tmp442r60m7']
[2023-12-03T19:16:27.757+0000] {standard_task_runner.py:85} INFO - Job 14: Subtask create_table
[2023-12-03T19:16:27.814+0000] {task_command.py:416} INFO - Running <TaskInstance: weather_scrapper.create_table manual__2023-12-03T19:16:25.432817+00:00 [running]> on host 046e595e6dd8
[2023-12-03T19:16:27.887+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_scrapper' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2023-12-03T19:16:25.432817+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-03T19:16:25.432817+00:00'
[2023-12-03T19:16:27.889+0000] {sql.py:274} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS measures (
            city VARCHAR(255),
            timestamp TIMESTAMP,
            temperature FLOAT,
            humidity FLOAT,
            cloudiness FLOAT,
            wind_speed FLOAT
        );
        
[2023-12-03T19:16:27.898+0000] {base.py:73} INFO - Using connection ID 'hw1_postgres' for task execution.
[2023-12-03T19:16:27.912+0000] {base.py:73} INFO - Using connection ID 'hw1_postgres' for task execution.
[2023-12-03T19:16:35.918+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 155, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "***" to address: Temporary failure in name resolution

[2023-12-03T19:16:35.927+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=weather_scrapper, task_id=create_table, execution_date=20231203T191625, start_date=20231203T191627, end_date=20231203T191635
[2023-12-03T19:16:35.947+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 14 for task create_table (could not translate host name "***" to address: Temporary failure in name resolution
; 359)
[2023-12-03T19:16:35.989+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-03T19:16:36.022+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
