[2023-12-03T19:26:59.215+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_scrapper.extract_group_Lviv.extract_data_Lviv manual__2023-12-03T19:26:49.266809+00:00 [queued]>
[2023-12-03T19:26:59.238+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_scrapper.extract_group_Lviv.extract_data_Lviv manual__2023-12-03T19:26:49.266809+00:00 [queued]>
[2023-12-03T19:26:59.240+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-03T19:26:59.284+0000] {taskinstance.py:1382} INFO - Executing <Task(SimpleHttpOperator): extract_group_Lviv.extract_data_Lviv> on 2023-12-03 19:26:49.266809+00:00
[2023-12-03T19:26:59.295+0000] {standard_task_runner.py:57} INFO - Started process 563 to run task
[2023-12-03T19:26:59.302+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'weather_scrapper', 'extract_group_Lviv.extract_data_Lviv', 'manual__2023-12-03T19:26:49.266809+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/weather_scrapper.py', '--cfg-path', '/tmp/tmp634kzbxb']
[2023-12-03T19:26:59.309+0000] {standard_task_runner.py:85} INFO - Job 26: Subtask extract_group_Lviv.extract_data_Lviv
[2023-12-03T19:26:59.423+0000] {task_command.py:416} INFO - Running <TaskInstance: weather_scrapper.extract_group_Lviv.extract_data_Lviv manual__2023-12-03T19:26:49.266809+00:00 [running]> on host 046e595e6dd8
[2023-12-03T19:26:59.654+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_scrapper' AIRFLOW_CTX_TASK_ID='extract_group_Lviv.extract_data_Lviv' AIRFLOW_CTX_EXECUTION_DATE='2023-12-03T19:26:49.266809+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-03T19:26:49.266809+00:00'
[2023-12-03T19:26:59.658+0000] {http.py:143} INFO - Calling HTTP method
[2023-12-03T19:26:59.692+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 145, in execute
    response = http.run(self.endpoint, self.data, self.headers, self.extra_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/hooks/http.py", line 145, in run
    session = self.get_conn(headers)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/hooks/http.py", line 98, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `weather_conn` isn't defined
[2023-12-03T19:26:59.707+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=weather_scrapper, task_id=extract_group_Lviv.extract_data_Lviv, execution_date=20231203T192649, start_date=20231203T192659, end_date=20231203T192659
[2023-12-03T19:26:59.758+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 26 for task extract_group_Lviv.extract_data_Lviv (The conn_id `weather_conn` isn't defined; 563)
[2023-12-03T19:26:59.798+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-03T19:26:59.824+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
