[2023-12-03T19:26:59.236+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_scrapper.extract_group_Kharkiv.extract_data_Kharkiv manual__2023-12-03T19:26:49.266809+00:00 [queued]>
[2023-12-03T19:26:59.262+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_scrapper.extract_group_Kharkiv.extract_data_Kharkiv manual__2023-12-03T19:26:49.266809+00:00 [queued]>
[2023-12-03T19:26:59.266+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-03T19:26:59.304+0000] {taskinstance.py:1382} INFO - Executing <Task(SimpleHttpOperator): extract_group_Kharkiv.extract_data_Kharkiv> on 2023-12-03 19:26:49.266809+00:00
[2023-12-03T19:26:59.320+0000] {standard_task_runner.py:57} INFO - Started process 565 to run task
[2023-12-03T19:26:59.329+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'weather_scrapper', 'extract_group_Kharkiv.extract_data_Kharkiv', 'manual__2023-12-03T19:26:49.266809+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/weather_scrapper.py', '--cfg-path', '/tmp/tmp1n25lvhe']
[2023-12-03T19:26:59.339+0000] {standard_task_runner.py:85} INFO - Job 28: Subtask extract_group_Kharkiv.extract_data_Kharkiv
[2023-12-03T19:26:59.456+0000] {task_command.py:416} INFO - Running <TaskInstance: weather_scrapper.extract_group_Kharkiv.extract_data_Kharkiv manual__2023-12-03T19:26:49.266809+00:00 [running]> on host 046e595e6dd8
[2023-12-03T19:26:59.687+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_scrapper' AIRFLOW_CTX_TASK_ID='extract_group_Kharkiv.extract_data_Kharkiv' AIRFLOW_CTX_EXECUTION_DATE='2023-12-03T19:26:49.266809+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-03T19:26:49.266809+00:00'
[2023-12-03T19:26:59.692+0000] {http.py:143} INFO - Calling HTTP method
[2023-12-03T19:26:59.730+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 145, in execute
    response = http.run(self.endpoint, self.data, self.headers, self.extra_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/hooks/http.py", line 145, in run
    session = self.get_conn(headers)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/hooks/http.py", line 98, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `weather_conn` isn't defined
[2023-12-03T19:26:59.736+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=weather_scrapper, task_id=extract_group_Kharkiv.extract_data_Kharkiv, execution_date=20231203T192649, start_date=20231203T192659, end_date=20231203T192659
[2023-12-03T19:26:59.759+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 28 for task extract_group_Kharkiv.extract_data_Kharkiv (The conn_id `weather_conn` isn't defined; 565)
[2023-12-03T19:26:59.835+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-03T19:26:59.952+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
